<?php

/**
 * @file
 * Contains user_admin_manager.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function user_admin_manager_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the user_admin_manager module.
    case 'help.page.user_admin_manager':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function user_admin_manager_theme() {
  return [
    'user_admin_manager' => [
      'render element' => 'children',
    ],
  ];
}
