<?php

/**
 * @file
 * Contains jazz_manage_users.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function jazz_manage_users_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the jazz_manage_users module.
    case 'help.page.jazz_manage_users':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function jazz_manage_users_theme($existing, $type, $theme, $path) {
  return [
    'jazz_manage_users' => [
      'render element' => 'children',
    ],
    // Views templates.
  'manage_user_views_view' => [
    'template' => 'manage-user-views-view',
    'base hook' => 'views_view',
    'path' => $path . '/templates/views'
  ],
  // Views unformatted templates.
  'manage_user_views_view_unformated' => [
    'template' => 'manage-user-views-view-unformated',
    'base hook' => 'views_view_unformatted',
    'path' => $path . '/templates/views'
  ],
  // Views unformatted templates.
  'manage_user_view_fields' => [
    'template' => 'manage-user-view-fields',
    'base hook' => 'views_view_fields',
    'path' => $path . '/templates/views'
  ],
  ];
}

/**
* Implements hook_theme_suggestions_page_alter().
*/
function jazz_manage_users_theme_suggestions_views_view_alter(array &$suggestions, array $variables)
{
$view = $variables['view'];
if ($view->id() == "manage_users" && $view->current_display == "page_1") {
  $suggestions[] = "manage_user_views_view";
}
}

/**
* Implements hook_theme_suggestions_HOOK_alter().
*
* Add views unformatted template suggestions.
* 
* @inheritdoc
*/
function jazz_manage_users_theme_suggestions_views_view_unformatted_alter(array &$suggestions, array $variables)
{
$view = $variables['view'];
if ($view->id() == "manage_users" && $view->current_display == "page_1") {
  $suggestions[] = "manage_user_views_view_unformated";
}
}

/**
* Implements hook_theme_suggestions_HOOK_alter().
*
* Add views unformatted template suggestions.
* 
* @inheritdoc
*/
function jazz_manage_users_theme_suggestions_views_view_fields_alter(array &$suggestions, array $variables)
{
$view = $variables['view'];
if ($view->id() == "manage_users" && $view->current_display == "page_1") {
  $suggestions[] = "manage_user_view_fields";
}
}

function jazz_manage_users_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'jazz_manage_users/jazz_manage_u';
}
