<?php

/**
 * @file
 * Contains ticketstatus.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ticketstatus_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ticketstatus module.
    case 'help.page.ticketstatus':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module to show ticket status with count') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ticketstatus_theme() {
  return [
    'ticket_status_block' => [
      'variables' => [
        'data' => []
      ],
      'render element' => 'children',
    ],
  ];
}
