<?php

/**
 * @file
 * Contains jazz_guides_blog.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function jazz_guides_blog_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the jazz_guides_blog module.
    case 'help.page.jazz_guides_blog':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function jazz_guides_blog_theme($existing, $type, $theme, $path) {
  return [
    'jazz_guides_blog' => [
      'render element' => 'children',
    ],

     // Views templates.
     'blog_guides_views_view' => [
      'template' => 'blog-guides-views-view',
      'base hook' => 'views_view',
      'path' => $path . '/templates/views'
    ],
    // Views unformatted templates.
    'blog_guides_views_view_unformated' => [
      'template' => 'blog-guides-views-view-unformated',
      'base hook' => 'views_view_unformatted',
      'path' => $path . '/templates/views'
    ],
    // Views unformatted templates.
    'blog_guides_view_fields' => [
      'template' => 'blog-guides-view-fields',
      'base hook' => 'views_view_fields',
      'path' => $path . '/templates/views'
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_page_alter().
 */
function jazz_guides_blog_theme_suggestions_views_view_alter(array &$suggestions, array $variables)
{
  $view = $variables['view'];
  if ($view->id() == "blogs" && $view->current_display == "guides") {
    $suggestions[] = "blog_guides_views_view";
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 *
 * Add views unformatted template suggestions.
 * 
 * @inheritdoc
 */
function jazz_guides_blog_theme_suggestions_views_view_unformatted_alter(array &$suggestions, array $variables)
{
  $view = $variables['view'];
  if ($view->id() == "blogs" && $view->current_display == "guides") {
    $suggestions[] = "blog_guides_views_view_unformated";
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 *
 * Add views unformatted template suggestions.
 * 
 * @inheritdoc
 */
function jazz_guides_blog_theme_suggestions_views_view_fields_alter(array &$suggestions, array $variables)
{
  $view = $variables['view'];
  if ($view->id() == "blogs" && $view->current_display == "guides") {
    $suggestions[] = "blog_guides_view_fields";
  }
}

