<?php

/**
 * @file
 * Contains jazz_help_article.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function jazz_help_article_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
      // Main module help for the jazz_help_article module.
    case 'help.page.jazz_help_article':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}


function jazz_help_article_preprocess(&$variables) {
  $variables['jazz_help_path'] = 'modules/custom/images';
  }



function jazz_help_article_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'jazz_help_article/jazz_home_articl';
}

/**
 * Implements hook_theme().
 */
function jazz_help_article_theme($existing, $type, $theme, $path)
{
  return [

    'jazz_help_article_block' => [
      'render element' => 'children',
      'variables' =>
      [
        'data' => [],
        'searchQuery' => null,
      ]
    ],
    'jazz_help_article' => [
      'render element' => 'children',
      'variables' =>
      [
        'data' => []
      ]
    ],
  ];
}
