<?php

/**
 * @file
 * Contains jazz_help_articles.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function jazz_help_articles_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
      // Main module help for the jazz_help_articles module.
    case 'help.page.jazz_help_articles':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function jazz_help_articles_theme($existing, $type, $theme, $path)
{
  return [
    'jazz_help_articles' => [
      'render element' => 'children',
      'variables' =>
      [
        'data' => []
      ]
    ],
    // 'jazz_help_articles2' => [
    //   'render element' => 'children',
    // ],
    // Views templates.
    'help_aritcles_views_view' => [
      'template' => 'help-aritcles-views-view',
      'base hook' => 'views_view',
      'path' => $path . '/templates/views'
    ],
    // Views unformatted templates.
    'help_aritcles_views_view_unformated' => [
      'template' => 'help-aritcles-views-view-unformated',
      'base hook' => 'views_view_unformatted',
      'path' => $path . '/templates/views'
    ],
    // Views unformatted templates.
    'help_aritcles_view_fields' => [
      'template' => 'help-aritcles-view-fields',
      'base hook' => 'views_view_fields',
      'path' => $path . '/templates/views'
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_page_alter().
 */
function jazz_help_articles_theme_suggestions_views_view_alter(array &$suggestions, array $variables)
{
  $view = $variables['view'];
  if ($view->id() == "help_articles" && $view->current_display == "page_1") {
    $suggestions[] = "help_aritcles_views_view";
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 *
 * Add views unformatted template suggestions.
 * 
 * @inheritdoc
 */
function jazz_help_articles_theme_suggestions_views_view_unformatted_alter(array &$suggestions, array $variables)
{
  $view = $variables['view'];
  if ($view->id() == "help_articles" && $view->current_display == "page_1") {
    $suggestions[] = "help_aritcles_views_view_unformated";
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 *
 * Add views unformatted template suggestions.
 * 
 * @inheritdoc
 */
function jazz_help_articles_theme_suggestions_views_view_fields_alter(array &$suggestions, array $variables)
{
  $view = $variables['view'];
  if ($view->id() == "help_articles" && $view->current_display == "page_1") {
    $suggestions[] = "help_aritcles_view_fields";
  }
}
